// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToFile(arg1, arg2) {
  return window['go']['main']['App']['AddTagToFile'](arg1, arg2);
}

export function AddTagToFiles(arg1, arg2) {
  return window['go']['main']['App']['AddTagToFiles'](arg1, arg2);
}

export function AutoCleanThumbnailCache(arg1) {
  return window['go']['main']['App']['AutoCleanThumbnailCache'](arg1);
}

export function BatchRenameFiles(arg1) {
  return window['go']['main']['App']['BatchRenameFiles'](arg1);
}

export function CanAccessPath(arg1) {
  return window['go']['main']['App']['CanAccessPath'](arg1);
}

export function CancelPaste(arg1) {
  return window['go']['main']['App']['CancelPaste'](arg1);
}

export function CancelSimilarImageSearch() {
  return window['go']['main']['App']['CancelSimilarImageSearch']();
}

export function CheckBatchRenameConflicts(arg1) {
  return window['go']['main']['App']['CheckBatchRenameConflicts'](arg1);
}

export function CheckSimilarImagesNeedReindex(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CheckSimilarImagesNeedReindex'](arg1, arg2, arg3, arg4);
}

export function ClearThumbnailCache() {
  return window['go']['main']['App']['ClearThumbnailCache']();
}

export function ClearUndoStack() {
  return window['go']['main']['App']['ClearUndoStack']();
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function ConvertChineseFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConvertChineseFiles'](arg1, arg2, arg3);
}

export function ConvertFile(arg1, arg2) {
  return window['go']['main']['App']['ConvertFile'](arg1, arg2);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DeleteFileRemark(arg1) {
  return window['go']['main']['App']['DeleteFileRemark'](arg1);
}

export function DeleteRenameScheme(arg1) {
  return window['go']['main']['App']['DeleteRenameScheme'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteToRecycleBin(arg1) {
  return window['go']['main']['App']['DeleteToRecycleBin'](arg1);
}

export function FindImagesSimilarTo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['FindImagesSimilarTo'](arg1, arg2, arg3, arg4, arg5);
}

export function FindSimilarImageGroups(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FindSimilarImageGroups'](arg1, arg2, arg3, arg4);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetConvertibleFormats(arg1) {
  return window['go']['main']['App']['GetConvertibleFormats'](arg1);
}

export function GetDefaultPaths() {
  return window['go']['main']['App']['GetDefaultPaths']();
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetFavoritePaths() {
  return window['go']['main']['App']['GetFavoritePaths']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetFileRemark(arg1) {
  return window['go']['main']['App']['GetFileRemark'](arg1);
}

export function GetFileTags(arg1) {
  return window['go']['main']['App']['GetFileTags'](arg1);
}

export function GetGlobalTags() {
  return window['go']['main']['App']['GetGlobalTags']();
}

export function GetLocalAuthToken() {
  return window['go']['main']['App']['GetLocalAuthToken']();
}

export function GetLocalServerPort() {
  return window['go']['main']['App']['GetLocalServerPort']();
}

export function GetPrivacyState() {
  return window['go']['main']['App']['GetPrivacyState']();
}

export function GetProtectedPaths(arg1) {
  return window['go']['main']['App']['GetProtectedPaths'](arg1);
}

export function GetRecentItems() {
  return window['go']['main']['App']['GetRecentItems']();
}

export function GetRenameSchemes() {
  return window['go']['main']['App']['GetRenameSchemes']();
}

export function GetSimilarImageGroups(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSimilarImageGroups'](arg1, arg2, arg3);
}

export function GetSimilarImageThresholds() {
  return window['go']['main']['App']['GetSimilarImageThresholds']();
}

export function GetTagUsageCounts() {
  return window['go']['main']['App']['GetTagUsageCounts']();
}

export function GetTagsForFiles(arg1) {
  return window['go']['main']['App']['GetTagsForFiles'](arg1);
}

export function GetThumbnailBudgetLimit() {
  return window['go']['main']['App']['GetThumbnailBudgetLimit']();
}

export function GetThumbnailCacheSize() {
  return window['go']['main']['App']['GetThumbnailCacheSize']();
}

export function InspectPathForNavigation(arg1) {
  return window['go']['main']['App']['InspectPathForNavigation'](arg1);
}

export function IsPathProtected(arg1) {
  return window['go']['main']['App']['IsPathProtected'](arg1);
}

export function LockPrivacyMode() {
  return window['go']['main']['App']['LockPrivacyMode']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function OpenFileWithDefault(arg1) {
  return window['go']['main']['App']['OpenFileWithDefault'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function OpenInTerminal(arg1) {
  return window['go']['main']['App']['OpenInTerminal'](arg1);
}

export function PasteFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['PasteFiles'](arg1, arg2, arg3);
}

export function PermanentDelete(arg1) {
  return window['go']['main']['App']['PermanentDelete'](arg1);
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadDirChunked(arg1, arg2) {
  return window['go']['main']['App']['ReadDirChunked'](arg1, arg2);
}

export function ReadFileText(arg1) {
  return window['go']['main']['App']['ReadFileText'](arg1);
}

export function RedoOperation() {
  return window['go']['main']['App']['RedoOperation']();
}

export function RemoveTagFromFile(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromFile'](arg1, arg2);
}

export function RemoveTagFromFiles(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromFiles'](arg1, arg2);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}

export function ResetPrivacyPassword(arg1, arg2) {
  return window['go']['main']['App']['ResetPrivacyPassword'](arg1, arg2);
}

export function ResolvePasteConflict(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolvePasteConflict'](arg1, arg2, arg3);
}

export function SaveRenameScheme(arg1, arg2) {
  return window['go']['main']['App']['SaveRenameScheme'](arg1, arg2);
}

export function SearchFiles(arg1) {
  return window['go']['main']['App']['SearchFiles'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetFileRemark(arg1, arg2) {
  return window['go']['main']['App']['SetFileRemark'](arg1, arg2);
}

export function SetPathProtected(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPathProtected'](arg1, arg2, arg3);
}

export function SetRestorePrivacyModeOnStartup(arg1) {
  return window['go']['main']['App']['SetRestorePrivacyModeOnStartup'](arg1);
}

export function SetTagProtected(arg1, arg2) {
  return window['go']['main']['App']['SetTagProtected'](arg1, arg2);
}

export function SetThumbnailBudgetLimit(arg1) {
  return window['go']['main']['App']['SetThumbnailBudgetLimit'](arg1);
}

export function SetupPrivacyPassword(arg1, arg2) {
  return window['go']['main']['App']['SetupPrivacyPassword'](arg1, arg2);
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function ToggleFavorite(arg1, arg2) {
  return window['go']['main']['App']['ToggleFavorite'](arg1, arg2);
}

export function UndoOperation() {
  return window['go']['main']['App']['UndoOperation']();
}

export function UnlockPrivacyMode(arg1) {
  return window['go']['main']['App']['UnlockPrivacyMode'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}

export function UpdateTagsOrder(arg1) {
  return window['go']['main']['App']['UpdateTagsOrder'](arg1);
}

export function VerifyWindowsIdentityForPrivacyReset() {
  return window['go']['main']['App']['VerifyWindowsIdentityForPrivacyReset']();
}

export function WriteFileText(arg1, arg2) {
  return window['go']['main']['App']['WriteFileText'](arg1, arg2);
}
