// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {chineseconv} from '../models';
import {rename} from '../models';

export function AddTagToFile(arg1:string,arg2:models.Tag):Promise<void>;

export function AddTagToFiles(arg1:Array<string>,arg2:models.Tag):Promise<void>;

export function AutoCleanThumbnailCache(arg1:number):Promise<void>;

export function BatchRenameFiles(arg1:Record<string, string>):Promise<void>;

export function CanAccessPath(arg1:string):Promise<boolean>;

export function CancelPaste(arg1:string):Promise<void>;

export function CancelSimilarImageSearch():Promise<void>;

export function CheckBatchRenameConflicts(arg1:Record<string, string>):Promise<Array<string>>;

export function CheckSimilarImagesNeedReindex(arg1:string,arg2:boolean,arg3:number,arg4:boolean):Promise<boolean>;

export function ClearThumbnailCache():Promise<void>;

export function ClearUndoStack():Promise<void>;

export function Close():Promise<void>;

export function ConvertChineseFiles(arg1:Array<string>,arg2:string,arg3:Array<chineseconv.CustomPair>):Promise<Array<string>>;

export function ConvertFile(arg1:string,arg2:string):Promise<string>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateTag(arg1:models.Tag):Promise<void>;

export function DeleteFileRemark(arg1:string):Promise<void>;

export function DeleteRenameScheme(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function DeleteToRecycleBin(arg1:Array<string>):Promise<void>;

export function FindImagesSimilarTo(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:boolean):Promise<Array<string>>;

export function FindSimilarImageGroups(arg1:string,arg2:boolean,arg3:number,arg4:boolean):Promise<Array<any>>;

export function GetConfig(arg1:string):Promise<string>;

export function GetConvertibleFormats(arg1:Array<string>):Promise<Array<string>>;

export function GetDefaultPaths():Promise<Record<string, string>>;

export function GetDrives():Promise<Array<string>>;

export function GetFavoritePaths():Promise<Array<string>>;

export function GetFavorites():Promise<Array<models.FileInfo>>;

export function GetFileDetail(arg1:string):Promise<models.FileDetail>;

export function GetFileRemark(arg1:string):Promise<string>;

export function GetFileTags(arg1:string):Promise<Array<models.Tag>>;

export function GetGlobalTags():Promise<Array<models.Tag>>;

export function GetLocalAuthToken():Promise<string>;

export function GetLocalServerPort():Promise<number>;

export function GetPrivacyState():Promise<models.PrivacyState>;

export function GetProtectedPaths(arg1:Array<string>):Promise<Record<string, boolean>>;

export function GetRecentItems():Promise<Array<models.FileInfo>>;

export function GetRenameSchemes():Promise<Array<rename.Scheme>>;

export function GetSimilarImageGroups(arg1:string,arg2:number,arg3:boolean):Promise<Array<any>>;

export function GetSimilarImageThresholds():Promise<Record<string, number>>;

export function GetTagUsageCounts():Promise<Record<string, number>>;

export function GetTagsForFiles(arg1:Array<string>):Promise<Record<string, Array<models.Tag>>>;

export function GetThumbnailBudgetLimit():Promise<number>;

export function GetThumbnailCacheSize():Promise<number>;

export function InspectPathForNavigation(arg1:string):Promise<models.PathInspection>;

export function IsPathProtected(arg1:string):Promise<boolean>;

export function LockPrivacyMode():Promise<models.PrivacyState>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function OpenFileWithDefault(arg1:string):Promise<void>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function PasteFiles(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function PermanentDelete(arg1:Array<string>):Promise<string>;

export function ReadDir(arg1:string):Promise<Array<models.FileInfo>>;

export function ReadDirChunked(arg1:string,arg2:string):Promise<Array<models.FileInfo>>;

export function ReadFileText(arg1:string):Promise<string>;

export function RecordInitialPath(arg1:string):Promise<void>;

export function RedoOperation():Promise<void>;

export function RemoveTagFromFile(arg1:string,arg2:string):Promise<void>;

export function RemoveTagFromFiles(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function RenameFile(arg1:string,arg2:string,arg3:boolean):Promise<boolean>;

export function ResetPrivacyPassword(arg1:string,arg2:string):Promise<models.PrivacyState>;

export function ResolvePasteConflict(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveRenameScheme(arg1:string,arg2:string):Promise<void>;

export function SearchFiles(arg1:Record<string, any>):Promise<Array<models.FileInfo>>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetFileRemark(arg1:string,arg2:string):Promise<void>;

export function SetPathProtected(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SetRestorePrivacyModeOnStartup(arg1:boolean):Promise<models.PrivacyState>;

export function SetTagProtected(arg1:string,arg2:boolean):Promise<void>;

export function SetThumbnailBudgetLimit(arg1:number):Promise<void>;

export function SetupPrivacyPassword(arg1:string,arg2:string):Promise<models.PrivacyState>;

export function StartTerminal(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:string,arg2:boolean):Promise<void>;

export function UndoOperation():Promise<void>;

export function UnlockPrivacyMode(arg1:string):Promise<models.PrivacyState>;

export function UpdateTag(arg1:models.Tag):Promise<void>;

export function UpdateTagsOrder(arg1:Array<string>):Promise<void>;

export function VerifyWindowsIdentityForPrivacyReset():Promise<boolean>;

export function WriteFileText(arg1:string,arg2:string):Promise<void>;
