// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToFile(arg1, arg2) {
  return window['go']['main']['App']['AddTagToFile'](arg1, arg2);
}

export function CancelPaste(arg1) {
  return window['go']['main']['App']['CancelPaste'](arg1);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function ConvertFile(arg1, arg2) {
  return window['go']['main']['App']['ConvertFile'](arg1, arg2);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteToRecycleBin(arg1) {
  return window['go']['main']['App']['DeleteToRecycleBin'](arg1);
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetConvertibleFormats(arg1) {
  return window['go']['main']['App']['GetConvertibleFormats'](arg1);
}

export function GetDefaultPaths() {
  return window['go']['main']['App']['GetDefaultPaths']();
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetFileTags(arg1) {
  return window['go']['main']['App']['GetFileTags'](arg1);
}

export function GetGlobalTags() {
  return window['go']['main']['App']['GetGlobalTags']();
}

export function GetLocalServerPort() {
  return window['go']['main']['App']['GetLocalServerPort']();
}

export function GetRecentItems() {
  return window['go']['main']['App']['GetRecentItems']();
}

export function GetTagsForFiles(arg1) {
  return window['go']['main']['App']['GetTagsForFiles'](arg1);
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function PasteFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['PasteFiles'](arg1, arg2, arg3);
}

export function PermanentDelete(arg1) {
  return window['go']['main']['App']['PermanentDelete'](arg1);
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function RemoveTagFromFile(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromFile'](arg1, arg2);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}

export function ResolvePasteConflict(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolvePasteConflict'](arg1, arg2, arg3);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}

export function UpdateTagsOrder(arg1) {
  return window['go']['main']['App']['UpdateTagsOrder'](arg1);
}
