// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTagToFile(arg1:string,arg2:models.Tag):Promise<void>;

export function CancelPaste(arg1:string):Promise<void>;

export function Close():Promise<void>;

export function ConvertFile(arg1:string,arg2:string):Promise<string>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateTag(arg1:models.Tag):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function DeleteToRecycleBin(arg1:Array<string>):Promise<void>;

export function GetConfig(arg1:string):Promise<string>;

export function GetConvertibleFormats(arg1:Array<string>):Promise<Array<string>>;

export function GetDefaultPaths():Promise<Record<string, string>>;

export function GetDrives():Promise<Array<string>>;

export function GetFileTags(arg1:string):Promise<Array<models.Tag>>;

export function GetGlobalTags():Promise<Array<models.Tag>>;

export function GetLocalServerPort():Promise<number>;

export function GetRecentItems():Promise<Array<models.FileInfo>>;

export function GetTagsForFiles(arg1:Array<string>):Promise<Record<string, Array<models.Tag>>>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function PasteFiles(arg1:string,arg2:Array<string>,arg3:string):Promise<string>;

export function PermanentDelete(arg1:Array<string>):Promise<string>;

export function ReadDir(arg1:string):Promise<Array<models.FileInfo>>;

export function RemoveTagFromFile(arg1:string,arg2:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string,arg3:boolean):Promise<boolean>;

export function ResolvePasteConflict(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function UpdateTag(arg1:models.Tag):Promise<void>;

export function UpdateTagsOrder(arg1:Array<string>):Promise<void>;
